version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  myapp:
    build: .
    image: webserver:latest
    ports: 
     - 5000:5000
    container_name: myapp
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    environment:
      - VIRTUAL_HOST=phrase.local
    depends_on: 
     - mongo

  mongo:
    image: mongo:4.2.5-bionic
    restart: always
    container_name: mymongo
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

