version: '3'
services:
  myapp:
    build: myapp/
    image: webserver:latest
    ports: 
     - 5000:5000
    container_name: myapp
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    depends_on: 
     - mongo

  mongo:
    image: mongo:4.2.5-bionic
    restart: always
    container_name: mymongo
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

